import gleam/string
import glimr/console/console
import shellout
import simplifile

/// Writes the migration into the database's _migrations
/// directory so the existing migration runner picks it up
/// automatically. The timestamp prefix ensures correct sort
/// order relative to other migrations. IF NOT EXISTS guards
/// make it safe to run the migration more than once without
/// failing on an already-created table or index.
///
pub fn run(database: String, table: String) -> Nil {
  let migrations_path = "src/data/" <> database <> "/_migrations"

  // Ensure migrations directory exists
  let _ = simplifile.create_directory_all(migrations_path)

  // Generate timestamp for filename
  let timestamp = get_timestamp()
  let filename = timestamp <> "_create_session_table.sql"
  let migration_path = migrations_path <> "/" <> filename

  // Generate the migration SQL
  let sql = "-- Generated by Glimr (sqlite)

CREATE TABLE IF NOT EXISTS " <> table <> " (
    id TEXT PRIMARY KEY,
    payload TEXT NOT NULL,
    last_activity INTEGER NOT NULL
);

-- Index for faster garbage collection lookups
CREATE INDEX IF NOT EXISTS idx_" <> table <> "_last_activity ON " <> table <> " (last_activity);
"

  case simplifile.write(migration_path, sql) {
    Ok(_) -> {
      console.output()
      |> console.line_success("Generated: " <> migration_path)
      |> console.print()
    }
    Error(_) -> {
      console.output()
      |> console.line_error("Failed to write migration file")
      |> console.print()
    }
  }
}

/// Migration files are ordered by filename, so the timestamp
/// prefix controls execution order. Shelling out to `date`
/// avoids pulling in a Gleam datetime library for this single
/// use. The zero fallback on failure still produces a valid
/// filename — the migration will just sort first.
///
fn get_timestamp() -> String {
  case shellout.command("date", ["+%Y%m%d%H%M%S"], ".", []) {
    Ok(output) -> string.trim(output)
    Error(_) -> "00000000000000"
  }
}
